email_from: jwhitehurst@kingcounty.gov
emails_qa: 
  - jwhitehurst@kingcounty.gov
emails_covid_vac:
  - jwhitehurst@kingcounty.gov
  - YARIDNI@kingcounty.gov
  - Dennis.Worsham@kingcounty.gov
  - Amy.Laurent@kingcounty.gov
  - Jeff.Duchin@kingcounty.gov
  - Atar.Baer@kingcounty.gov
  - spogosjans@kingcounty.gov
  - Libby.Page@kingcounty.gov
  - kasykes@kingcounty.gov
  - Meagan.Kay@kingcounty.gov
  - mathanson@kingcounty.gov
  - Richard.Harruff@kingcounty.gov
  - n-gcrawbuck@kingcounty.gov
