Addresses:
  Id: INTEGER
  ZipCode: NVARCHAR(255)
  City: NVARCHAR(255)
  stte: NVARCHAR(255)
  County: NVARCHAR(255)
  Country: NVARCHAR(255)
  Addr: NVARCHAR(255)
  Township: NVARCHAR(255)
  Lat: NVARCHAR(255)
  Long: NVARCHAR(255)
Autopsies:
  Id: INTEGER
  ExamTypeId: INTEGER
  ExamDate: DATE
  ExamTime: INTEGER
  ExamTimeStr: NVARCHAR(255)
  PathologistId: INTEGER
  AutopsyRptSignedDate: DATE
  AutopsyTypeId: INTEGER
  AutopsyLocationId: INTEGER
  PathologistAssistantId: INTEGER
  InfectiousDiseaseId: INTEGER
  PolicePresentId: INTEGER
  ExamCompleteDate: DATE
  ExamCompleteTime: INTEGER
  AutopsyReportId: INTEGER
  GeneralAutopsyFindings: NVARCHAR(MAX)
  PriorAutopsyId: INTEGER
  ResidentInvolvedId: INTEGER
  FellowId: INTEGER
  DetailsInfectiousDisease: NVARCHAR(MAX)
  ExpPrelAutReportDate: DATE
  PrelAutReportApprovedId: INTEGER
  PrelAutReportReceivedId: INTEGER
  ExpFinalAutReportDate: DATE
  FinalAutReportReceivedId: INTEGER
Cases:
  Id: INTEGER
  CaseNum: NVARCHAR(255)
  CCaseNum: NVARCHAR(255)
  CaseTypeId: INTEGER
  EnteredDate: DATE
  EnteredTime: INTEGER
  EnteredById: INTEGER
  LastUpdatedById: INTEGER
  LastUpdatedDate: DATE
  LastUpdatedTime: INTEGER
  FuneralHome: NVARCHAR(255)
  FuneralHomeId: INTEGER
  CaseStatusId: INTEGER
  IsIndigentId: INTEGER
  DoeTrackNum: INTEGER
  MannerOfDeathId: INTEGER
  SubMannerOfDeathId: INTEGER
  InvestigatorId: INTEGER
  PublicAdminCaseId: INTEGER
  Scene: BIT
  Letter: BIT
  Fees: BIT
  BodyTransport: BIT
  CremationOnly: BIT
  Cremation: BIT
  Invoiced: BIT
  CremationAuthorizedById: INTEGER
  CremationAuthorizedDate: DATE
  BillingFeeInfoId: INTEGER
  AutopsyPerformedId: INTEGER
  PregnantDuringLastYearId: INTEGER
  CallDate: DATE
  CallTime: INTEGER
  CremationDate: DATE
  CremationWeived: BIT
  CremationComments: NVARCHAR(MAX)
  CremationAuthorizedTime: INTEGER
  CremationApprovedDate: DATE
  CremationApprovedTime: INTEGER
  CremationApprovedById: INTEGER
  InCustodyDeathId: INTEGER
  HospitalDeathId: INTEGER
  FireDeathId: INTEGER
  SUIDIDeathId: INTEGER
  StillbornNewbornDeathId: INTEGER
  FallCrushDeathId: INTEGER
  MVCDeathId: INTEGER
  CommonAttributesInfId: INTEGER
  HomicideDeathId: INTEGER
  SuicideHomicideDeathId: INTEGER
  SceneEnviromentInfId: INTEGER
  TrainDeathId: INTEGER
  AircraftDeathId: INTEGER
  SuicideDeathId: INTEGER
  DrowningDeathId: INTEGER
  DivingDeathId: INTEGER
  WorkRelatedDeathId: INTEGER
  PoisonDeathId: INTEGER
  SportDeathId: INTEGER
  LightningDeathId: INTEGER
  SkeletalRemainsDeathId: INTEGER
  CuttingAndStabbingDeathId: INTEGER
  HangingDeathId: INTEGER
  InfectiousDiseaseDeathId: INTEGER
  AnimalReptileInsectDeathId: INTEGER
  ElectrocutionDeathId: INTEGER
  ExposureEnvDeathId: INTEGER
  FirearmDeathId: INTEGER
  CarbonMonoxideDeathId: INTEGER
  SurgicalDeathId: INTEGER
  WaterDeathId: INTEGER
  PermitNumber: INTEGER
  TraumaIn6MonthId: INTEGER
  NextOfKinId: INTEGER
  HealthCareAgentId: INTEGER
  AttendingPhysicianId: INTEGER
  HistoryOfFallsOrTraumaId: INTEGER
  DateLastSeen: DATE
  DiagExpCauseOfDeath: NVARCHAR(MAX)
  AnyFallsInjury: NVARCHAR(MAX)
  EdrsId: NVARCHAR(MAX)
  EdrsLocked: BIT
  EdrsReviewed: BIT
  BodyToKCMEOId: INTEGER
  DutyPathContactedById: INTEGER
  DutyPathContactedId: INTEGER
  AutopsyId: INTEGER
  BodyId: INTEGER
  CaseClosureId: INTEGER
  DeathCertificateId: INTEGER
  DeathLocationId: INTEGER
  DecedentId: INTEGER
  IdentificationAttemptId: INTEGER
  IncidentId: INTEGER
  MedicalHistoryId: INTEGER
  NarrativeId: INTEGER
  LabSpecimenNumber: NVARCHAR(255)
  ReadOnly: BIT
  WorkflowCompleted: BIT
  Reopened: BIT
  DateNMSReceived: DATE
  NMSNumber: NVARCHAR(255)
  CreatedFromExpectedCase: BIT
  PendingNotification: INTEGER
  Reviewed: BIT
  NonReportableId: INTEGER
  TransferredToAgencyId: INTEGER
  TransferredToContactId: INTEGER
  TransferredDate: DATE
  TransferredTime: INTEGER
  TransferredAcceptedId: INTEGER
  HighProfileId: INTEGER
  HHSId: INTEGER
  WitnessLastBreathDate: DATE
  WitnessLastBreathTime: INTEGER
  WitnessLastBreathById: INTEGER
  PressReleaseId: INTEGER
  TimeLineId: INTEGER
  HHSReferralId: INTEGER
  ElderAbuseId: INTEGER
  ExposureId: INTEGER
  ArrestRelatedId: INTEGER
  MecapId: INTEGER
  CFRPTId: INTEGER
  VDRId: INTEGER
  CCIId: INTEGER
  CFRTId: INTEGER
  EmbalmedBeforeSmplesWereTakenId: INTEGER
  DrugsSuspected: NVARCHAR(255)
  IsLegacy: BIT
  IDrug: BIT
  IDrugSent: BIT
  CremationInvoiceId: INTEGER
  MultipleIncidentId: INTEGER
  PathologyClearedDateTimeAlertDone: BIT
  PathologyClearedDateTimeReportPrint: BIT
  CertifyingPhysicianContactedById: INTEGER
  ProbableCauseId: INTEGER
  Investigator2Id: INTEGER
DeathCertificates:
  Id: INTEGER
  HowInjury: NVARCHAR(MAX)
  SignedById: INTEGER
  DateCompleted: DATETIME
  CODEnteredById: INTEGER
  PreliminaryCauseOfDeath: NVARCHAR(255)
  CauseAId: INTEGER
  OtherCause: NVARCHAR(MAX)
  PathologyClearedDateTime: DATETIME
  TobaccoUseContributed: BIT
  CauseHeroinRelatedId: INTEGER
  CauseOfHoldId: INTEGER
  CauseHoldOther: NVARCHAR(MAX)
  AutopsyPerformedId: INTEGER
  DrugRelated: BIT
  CauseCleared: BIT
  CauseClearedWithVitalId: INTEGER
  CauseClearedWithVitalDate: DATETIME
  CauseClearedWithVitalById: INTEGER
  FirstTimeCauseCompleted: BIT
  DeathCertificateCODAmendedById: INTEGER
  CauseClearedWithVitalDateTime: DATETIME
  NeedForAffidavitStatus: INTEGER
DeathCertificateCauses:
  Id: INTEGER
  DeathCause: NVARCHAR(255)
  Interval: NVARCHAR(255)
  DeathCertificateId: INTEGER
DeathLocations:
  Id: INTEGER
  ReportedDate: DATE
  ReportedTime: INTEGER
  ReportedTimeStr: NVARCHAR(255)
  ReasonReportedId: INTEGER
  RptdByOrgId: INTEGER
  RptdByNameId: INTEGER
  RptdReceivedById: INTEGER
  DeathPronouncedById: INTEGER
  DeathPlaceTypeId: INTEGER
  DeathPlaceOrganizationId: INTEGER
  DeathPlace: NVARCHAR(MAX)
  DeathAddressId: INTEGER
  DeathPlacePhone: NVARCHAR(255)
  SameAddressAsDecedent: BIT
  RemovedFromScene: NVARCHAR(255)
  PronouncedDate: DATE
  PronouncedTime: INTEGER
  IfHospitalId: INTEGER
  DeathInCityId: INTEGER
  CaseIdTmp: INTEGER
Decedents:
  Id: INTEGER
  BirthDate: DATE
  BirthTime: INTEGER
  AddressId: INTEGER
  PlaceOfBirthTypeId: INTEGER
  PlaceOfBirthOrganizationId: INTEGER
  PlaceOfBirth: NVARCHAR(255)
  PlaceOfBirthAddressId: INTEGER
  SSN: NVARCHAR(MAX)
  EthnicityId: INTEGER
  MaritalStatusId: INTEGER
  DriverLicenseNumber: NVARCHAR(255)
  DriverLicenseStateId: INTEGER
  PassportNumber: NVARCHAR(255)
  PassportIssueDate: DATE
  PassportIssueCountry: NVARCHAR(255)
  DeathDate: DATE
  DeathTime: INTEGER
  SameAddressAsDeathLocation: INTEGER
  Citizen: NVARCHAR(255)
  HomelessId: INTEGER
  ImmigrantId: INTEGER
  AgeYears: INTEGER
  AgeYearsStr: NVARCHAR(255)
  AgeMonths: INTEGER
  AgeDays: INTEGER
  AgeHours: INTEGER
  AgeMinutes: INTEGER
  PhoneResidence: NVARCHAR(255)
  DeathDateEstId: INTEGER
  BirthDateStateId: INTEGER
  EducationYearCompId: INTEGER
  ResCityYearsId: INTEGER
  MobilePhone: NVARCHAR(255)
  VeteranId: INTEGER
  VetServiceSerialNum: NVARCHAR(255)
  VetVAFileNum: NVARCHAR(255)
  YearsOfServiceId: INTEGER
  VetServiceDateFrom: DATE
  VetServiceDateTo: DATE
  Rank: NVARCHAR(MAX)
  Branch: NVARCHAR(MAX)
  ServiceNumber: NVARCHAR(255)
  VAContactedId: INTEGER
  OccupationTradeId: INTEGER
  KindOfBusinessIndustry: NVARCHAR(255)
  TimeInOccupationId: INTEGER
  TimeWithEmployerId: INTEGER
  JobPossition: NVARCHAR(255)
  EmployerId: INTEGER
  PhoneEmployer: NVARCHAR(255)
  MailingAddressId: INTEGER
  GenderId: INTEGER
  IDnumber: INTEGER
  PassportExpirationDate: DATE
  CUStudentId: INTEGER
  TransientId: INTEGER
  ContactedConsulateId: INTEGER
  BrainDeathId: INTEGER
  DeclOfCardiacDeathDate: DATE
  DeclOfCardiacDeathTime: INTEGER
  TransgenderId: INTEGER
  SexualOrientationId: INTEGER
  IllegalImmigrantId: INTEGER
  RaceId: INTEGER
  OccupationTrade: NVARCHAR(255)
Decedents_Items:
  Id: INTEGER
  Id2: INTEGER
Incidents:
  Id: INTEGER
  Discriminator: NVARCHAR(255)
  IncidentPlaceTypeId: INTEGER
  IncidentPlaceOrganizationId: INTEGER
  IncidentPlace: NVARCHAR(255)
  AddressId: INTEGER
  SameAddressAsDeathLocation: BIT
  SameAddressAsDecedent: BIT
  IncidentDate: DATE
  IncidentDateUnknowndId: INTEGER
  IncidentTime: INTEGER
  IncidentTimeStr: NVARCHAR(255)
  IncidentTimeUnknownId: INTEGER
  IncidentTimeEstId: INTEGER
  FirearmTypeId: INTEGER
  SharpImpTypeId: INTEGER
  FoundDate: DATE
  FoundTime: INTEGER
  LastSeenAliveDate: DATE
  LastSeenAliveTime: INTEGER
  LastSeenAliveById: INTEGER
  MecapInformationId: INTEGER
  FoundById: INTEGER
  IncidentPlacePhone: NVARCHAR(255)
  InjuryLocationDescription: NVARCHAR(MAX)
  SealedId: INTEGER
  PhotosOfIncidentTakenById: INTEGER
  VideoOfIncidentTakenById: INTEGER
  PhotosOfIncidentInjuryTakenId: INTEGER
  VideoOfIncidentInjuryTakenId: INTEGER
  WhereTempTakenOnBody: NVARCHAR(255)
  DecompositionId: INTEGER
  HowWasDecClothed: NVARCHAR(255)
  FrothId: INTEGER
  FrothColor: NVARCHAR(255)
  MEAtSceneId: INTEGER
  FirearmCaliberId: INTEGER
  TypeofProjectileId: INTEGER
  InvestigatorTimesId: INTEGER
  ClothingCutAwayById: INTEGER
  ClothingCutAwayDate: DATE
  ClothingCutAwayTime: INTEGER
  DrugUseSuspectedId: INTEGER
  AlcoholUseSuspectedId: INTEGER
  ConsentToSearchId: INTEGER
  ConsentGivenById: INTEGER
  FoundAgencyId: INTEGER
  AlcoholUseSuspectedDesc: NVARCHAR(MAX)
  AlcoholUseDescription: NVARCHAR(MAX)
  TransportationInjuryId: INTEGER
  MFINumber: NVARCHAR(255)
  CaseTypeId: INTEGER
IncidentInvAgencies:
  Id: INTEGER
  InvAgencyId: INTEGER
  InvOfficerId: INTEGER
  InvAgencyRptNum: NVARCHAR(255)
  PrimaryInvAgencyId: INTEGER
  EnteredById: INTEGER
  EnteredDate: DATE
  EnteredTime: INTEGER
  IncidentId: INTEGER
Items:
  Id: INTEGER
  Deleted: BIT
  Description: NVARCHAR(255)
  Code: NVARCHAR(255)
  Removeable: BIT
  ListOfItems: INTEGER
  Order: INTEGER
  Active: BIT
ListOfItems:
  Id: INTEGER
  nme: NVARCHAR(255)
  NotifyBy: NVARCHAR(255)
  Deleted: BIT
  NotifyList: NVARCHAR(255)
  SortType: INTEGER
NamesData:
  Id: INTEGER
  Type: INTEGER
  FirstName: NVARCHAR(255)
  MiddleName: NVARCHAR(255)
  LastName: NVARCHAR(255)
  MaidenName: NVARCHAR(255)
  Prefix: NVARCHAR(255)
  Suffix: NVARCHAR(255)
  Credentials: NVARCHAR(255)
  CompleteName: NVARCHAR(255)
  Legacy: NVARCHAR(255)
Narratives:
  Id: INTEGER
  NarrEnteredById: INTEGER
  NarrEnteredDate: DATE
  Synopsis: NVARCHAR(MAX)
  NarrativeDet: NVARCHAR(MAX)
  NarrEnteredTime: INTEGER
  NarrSceneDescription: NVARCHAR(MAX)
  NarrBodyCondition: NVARCHAR(MAX)
  NarrSocialHistory: NVARCHAR(MAX)
  NarrDisposition: NVARCHAR(MAX)
  NarrMedicalHistory: NVARCHAR(MAX)
Organizations:
  Id: INTEGER
  Aliascode: NVARCHAR(255)
  Active: BIT
  nme: NVARCHAR(255)
  AddressId: INTEGER
  Phone: NVARCHAR(255)
  Fax: NVARCHAR(255)
  DirectorName: NVARCHAR(255)
  Email: NVARCHAR(255)
  OrganizationCategoryId: INTEGER
  Deleted: BIT
  BillingCode: NVARCHAR(255)
  ManualBilling: BIT
OrganizationsCategories:
  Id: INTEGER
  Code: NVARCHAR(255)
  Description: NVARCHAR(255)
  CommonPlace: BIT
  Destroyed: BIT
ToxResults:
  Id: INTEGER
  EnteredById: INTEGER
  EnteredDate: DATE
  EnteredTime: INTEGER
  Test: NVARCHAR(255)
  Analyte: NVARCHAR(255)
  UnitsOfMeasure: NVARCHAR(255)
  Result: NVARCHAR(255)
  CausedDeathId: INTEGER
  IllicitId: INTEGER
  Notes: NVARCHAR(255)
  ResultStatus: NVARCHAR(255)
  Specimen: NVARCHAR(255)
  Deleted: BIT
  Range: NVARCHAR(255)
  SubstanceRoleId: INTEGER
  CaseId: INTEGER
  QualitativeResult: NVARCHAR(255)
  QuantResultRangeId: INTEGER
